name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name : checkoutcode
        uses: actions/checkout@v3
      - name : validaciones
        run: ls -la
      - name: list the directory
        run: git show --pretty="format:" --name-only
