name: Validate-Encoding
on: ['pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : checkoutcode
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name : file list
        run: git branch --show-current
      - name: Validate Encoding in Files
        run: git show --pretty="format:" --name-only
