name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name : checkoutcode
        uses: actions/checkout@v3
      - name : validaciones
        run: ls -la
      - name: list the directory
        run: for i in $(git show --pretty="format:" --name-only);do if [[ -e $i ]] && [[ 'file -b --mime-encoding $i' !=  us-ascii ]]; then echo "es archivo sin utf-8"; fi;done;
