name: Validate-Encoding
on: ['pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : checkoutcode
        uses: actions/checkout@${GITHUB_REF}
      - name : file list
        run: ls -la
      - name: Validate Encoding in Files
        run: git branch
